routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('landing');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

//Landing Page
Route::get('/home', 'HomeController@index')->name('home');
Route::get('landing', 'landingController@index');

//Beranda
Route::get('beranda', 'berandaController@index');

//Stok Darah
Route::resource('stok', 'stokController');
Route::post('/updateStok', ['as' => 'updateStok', 'uses' => 'stokController@update']);

//Permintaan
Route::resource('permintaan', 'permintaanController');
Route::get('/validasiPermintaan/{id}', ['as' => 'validasiPermintaan', 'uses' => 'permintaanController@validasi']);
Route::get('/batalkanPermintaan/{id}', ['as' => 'batalkanPermintaan', 'uses' => 'permintaanController@batalvalidasi']);

//Pendonor
Route::resource('pendonor', 'pendonorController');
Route::post('/updatePendonor', ['as' => 'updatePendonor', 'uses' => 'pendonorController@update']);
Route::get('/hapusPendonor/{id}', ['as' => 'hapusPendonor', 'uses' => 'pendonorController@destroy']);

//Donor
Route::resource('donor', 'donorController');
Route::post('/updateDonor', ['as' => 'updateDonor', 'uses' => 'donorController@update']);
Route::get('/hapusDonor/{id}', ['as' => 'hapusDonor', 'uses' => 'donorController@destroy']);

//Peramalan
Route::resource('peramalan', 'peramalanController');

resources/views/inventory/beranda.blade.php
@extends('layouts.header')
@section('title')
    Beranda - Inventory
@endsection

@section('isiLuarAtas')
    Beranda
@endsection

@section('konten')
    <!-- Widgets -->
    <div class="row clearfix">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-pink hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">opacity</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Stok Darah A</div>
                    <div class="number count-to">{{$stoka}}</div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-cyan hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">opacity</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Stok Darah B</div>
                    <div class="number count-to">{{$stokb}}</div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-light-green hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">opacity</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Stok Darah AB</div>
                    <div class="number count-to">{{$stokab}}</div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-orange hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">opacity</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Stok Darah O</div>
                    <div class="number count-to">{{$stoko}}</div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Widgets -->

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="body text-center">
                    <img src="{{ asset('images/logo_pmi.png') }}" style="height: 250px;">
                    <h1>Selamat Datang {{ Auth::user()->name }}</h1>
                    <p class="m-b-30">
                        Selamat datang di Sistem Informasi UTD PMI Kab. Jombang. Silahkan pilih menu yang tersedia untuk mulai mengoperasikan sistem informasi ini.
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('isiLuar')

@endsection

resources/views/inventory/detailStok.blade.php
@extends('layouts.header')
@section('title')
    Detail Stok Darah - Inventory
@endsection

@section('isiLuarAtas')
    Detail Stok Darah
@endsection

@section('konten')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Tabel Detail Stok Darah
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-responsive table-bordered table-striped table-hover js-basic-example dataTable" style="width:100%;">
                            <thead>
                            <tr>
                                <th>No. Kantong</th>
                                <th>Komponen</th>
                                <th>Golongan Darah</th>
                                <th>Tanggal Donor</th>
                                <th>Tanggal Kadaluarsa</th>
                                <th>Nama Pendonor</th>
                                <th>Jenis</th>
                                <th>Aksi</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($data as $a)
                                <tr>
                                    <td>{{ $a->noKantong }}</td>
                                    <td>{{ $a->komponen }}</td>
                                    <td>{{ $a->golDarah }}</td>
                                    <td>{{ $a->tglDonor }}</td>
                                    <td>{{ $a->tglKadaluarsa }}</td>
                                    <td>{{ $a->namaPendonor }}</td>
                                    <td>{{ $a->jenis }}</td>
                                    <td class="text-center">
                                        <a href="javascript:;" class="editstok" data-idkantong="{{ $a->noKantong }}" data-iddonor="{{ $a->idDonor }}" data-komponen="{{ $a->komponen }}" data-tglkadaluarsa="{{ $a->tglKadaluarsa }}" data-jenis="{{ $a->jenis }}"><i class="material-icons">edit</i></a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <a class="btn bg-orange waves-effect" href="{{ url('/stok') }}">
        Kembali
    </a>
@endsection

@section('isiLuar')
    <div class="modal fade" id="editstok" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="largeModalLabel">Edit Stok</h4>
                </div>
                <div class="modal-body">
                    {!! Form::open(['url'=>route('updateStok')]) !!}
                    <div class="row clearfix">
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="form-line">
                                    <label>Nomor Kantong</label>
                                    <input id="id_kantong" name="noKantong" type="text" class="form-control" placeholder="ID Kantong" readonly>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row clearfix">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label>ID Donor</label>
                                    <select name="idDonor" id="iddonor" type="text" class="form-control" data-live-search="true">
                                        <option value="">-- ID Donor --</option>
                                        @foreach ($donor as $d)
                                            <option value="{{ $d->idDonor}}">{{$d->idDonor}}. {{$d->noKTP}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label>Komponen</label>
                                    <select id="komponen" name="komponen" class="form-control">
                                        <option value="">-- Komponen --</option>
                                        <option value="WB">WB</option>
                                        <option value="PRC">PRC</option>
                                        <option value="TC">TC</option>
                                        <option value="LP">LP</option>
                                        <option value="FFP">FFP</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row clearfix">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label>Tanggal Kadaluarsa</label>
                                    <input id="tgl_kadaluarsa" name="tglKadaluarsa" type="text" class="form-control datepicker" placeholder="Tanggal Kadaluarsa">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label>Jenis</label>
                                    <select id="jenis" name="jenis" class="form-control">
                                        <option>-- Jenis --</option>
                                        <option value="single">single</option>
                                        <option value="double">double</option>
                                        <option value="triple">triple</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-link waves-effect">SIMPAN</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">TUTUP</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/inventory/stok.blade.php
@extends('layouts.header')
@section('title')
    Stok Darah - Inventory
@endsection

@section('isiLuarAtas')
    Stok Darah
@endsection

@section('konten')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Tabel Stok Darah
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-responsive table-bordered table-striped table-hover js-basic-example dataTable" style="width:100%;">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>Komponen</th>
                                <th>Golongan Darah</th>
                                <th>Stok</th>
                                <th>Aksi</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $no=1 ?>
                            @foreach($data as $a)
                                <tr>
                                    <td>{{ $no }}</td>
                                    <td>{{ $a->komponen }}</td>
                                    <td>{{ $a->golDarah }}</td>
                                    <td>
                                        <?php $d = DB::table('tb_donor')->join('tb_kantong', 'tb_kantong.idDonor', '=', 'tb_donor.idDonor')->join('tb_pendonor', 'tb_donor.noKTP', '=', 'tb_pendonor.noKTP')->where([['komponen', '=', $a->komponen], ['golDarah', '=', $a->golDarah],])->get() ?>
                                        {{ $stok = count($d) }}
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ route("stok.show", $a->komponen) }}" class=""><i class="material-icons">search</i></a>
                                    </td>
                                </tr>
                                <?php $no++;?>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('isiLuar')
    <button type="button" class="btn bg-red waves-effect" data-toggle="modal" data-target="#largeModal">
        Tambah Stok
    </button>
    <div class="modal fade" id="largeModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="largeModalLabel">Tambah Stok</h4>
                </div>
                <div class="modal-body">
                    {!! Form::open(['url'=>route('stok.store')]) !!}
                    <div class="row clearfix">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label>ID Donor</label>
                                    <select name="idDonor" id="idDonor" type="text" class="form-control" placeholder="ID Donor">
                                        <option value="">-- ID Donor --</option>
                                        @foreach ($donor as $d)
                                            <option value="{{ $d->idDonor}}">{{$d->idDonor}}. {{$d->noKTP}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label>Komponen</label>
                                    <select name="komponen" class="form-control">
                                        <option value="">-- Komponen --</option>
                                        <option value="WB">WB</option>
                                        <option value="PRC">PRC</option>
                                        <option value="TC">TC</option>
                                        <option value="LP">LP</option>
                                        <option value="FFP">FFP</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row clearfix">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label>Tanggal Kadaluarsa</label>
                                    <input name="tglKadaluarsa" type="text" class="form-control datepicker"
                                           placeholder="Tanggal Kadaluarsa">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <label>Jenis</label>
                                    <select name="jenis" class="form-control">
                                        <option value="">-- Jenis --</option>
                                        <option value="single">single</option>
                                        <option value="double">double</option>
                                        <option value="triple">triple</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-link waves-effect">SIMPAN</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">TUTUP</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection