routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('landing');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

//Landing Page
Route::get('/home', 'HomeController@index')->name('home');
Route::get('landing', 'landingController@index');

//Beranda
Route::get('beranda', 'berandaController@index');

//Stok Darah
Route::resource('stok', 'stokController');
Route::post('/updateStok', ['as' => 'updateStok', 'uses' => 'stokController@update']);

//Permintaan
Route::resource('permintaan', 'permintaanController');
Route::get('/validasiPermintaan/{id}', ['as' => 'validasiPermintaan', 'uses' => 'permintaanController@validasi']);
Route::get('/batalkanPermintaan/{id}', ['as' => 'batalkanPermintaan', 'uses' => 'permintaanController@batalvalidasi']);

//Pendonor
Route::resource('pendonor', 'pendonorController');
Route::post('/updatePendonor', ['as' => 'updatePendonor', 'uses' => 'pendonorController@update']);
Route::get('/hapusPendonor/{id}', ['as' => 'hapusPendonor', 'uses' => 'pendonorController@destroy']);

//Donor
Route::resource('donor', 'donorController');
Route::post('/updateDonor', ['as' => 'updateDonor', 'uses' => 'donorController@update']);
Route::get('/hapusDonor/{id}', ['as' => 'hapusDonor', 'uses' => 'donorController@destroy']);

//Peramalan
Route::resource('peramalan', 'peramalanController');

resources/views/admin/beranda.blade.php
@extends('layouts.header')
@section('title')
    Beranda - Admin
@endsection

@section('isiLuarAtas')
    Beranda
@endsection

@section('konten')
    <!-- Widgets -->
    <div class="row clearfix">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-pink hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">assignment</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Total Permintaan</div>
                    <div class="number count-to">{{$totalpermintaan}}</div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-cyan hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">people</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Pendonor</div>
                    <div class="number count-to">{{$pendonor}}</div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-light-green hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">opacity</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Stok Darah</div>
                    <div class="number count-to">{{$stok}}</div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-orange hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">local_hospital</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Manajer Rumah Sakit</div>
                    <div class="number count-to">{{$manajer}}</div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Widgets -->

    <!-- Grafik Permintaan -->
    <div class="row clearfix">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="header">
                    <div class="row clearfix">
                        <div class="col-xs-12 col-sm-6">
                            <h2>Grafik Permintaan Tahun {{date('Y')}}</h2>
                        </div>
                    </div>
                </div>
                <div class="body">
                    <canvas id="myChart" height="100"></canvas>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Grafik Permintaan -->
@endsection

@section('isiLuar')
    <!-- ChartJs -->
    <script src="{{asset('plugins/chartjs/Chart.bundle.js')}}"></script>
    <script>
        var ctx = document.getElementById("myChart").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"],
                datasets: [{
                    label: 'Permintaan',
                    data: [{{$permintaan[1]}}, {{$permintaan[2]}}, {{$permintaan[3]}}, {{$permintaan[4]}}, {{$permintaan[5]}}, {{$permintaan[6]}}, {{$permintaan[7]}}, {{$permintaan[8]}}, {{$permintaan[9]}}, {{$permintaan[10]}}, {{$permintaan[11]}}, {{$permintaan[12]}}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(255, 99, 132, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(255,99,132,1)',
                        'rgba(255,99,132,1)',
                        'rgba(255,99,132,1)',
                        'rgba(255,99,132,1)',
                        'rgba(255,99,132,1)',
                        'rgba(255,99,132,1)',
                        'rgba(255,99,132,1)',
                        'rgba(255,99,132,1)',
                        'rgba(255,99,132,1)',
                        'rgba(255,99,132,1)',
                        'rgba(255,99,132,1)'
                    ],
                    borderWidth: 1
                },
                    {
                        label: 'Permintaan Terpenuhi',
                        data: [{{$permintaanterpenuhi[1]}}, {{$permintaanterpenuhi[2]}}, {{$permintaanterpenuhi[3]}}, {{$permintaanterpenuhi[4]}}, {{$permintaanterpenuhi[5]}}, {{$permintaanterpenuhi[6]}}, {{$permintaanterpenuhi[7]}}, {{$permintaanterpenuhi[8]}}, {{$permintaanterpenuhi[9]}}, {{$permintaanterpenuhi[10]}}, {{$permintaanterpenuhi[11]}}, {{$permintaanterpenuhi[12]}}],
                        backgroundColor: [
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(54, 162, 235, 0.2)',
                            'rgba(54, 162, 235, 0.2)'
                        ],
                        borderColor: [
                            'rgba(54, 162, 235, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(54, 162, 235, 1)',
                            'rgba(54, 162, 235, 1)'
                        ],
                        borderWidth: 1
                    }
                ]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true
                        }
                    }]
                }
            }
        });
    </script>
@endsection

resources/views/admin/peramalan.blade.php
@extends('layouts.header')
@section('title')
    Peramalan Permintaan - Admin
@endsection

@section('isiLuarAtas')
    Peramalan Permintaan
@endsection

@section('konten')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Tabel Peramalan
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-responsive table-bordered table-striped table-hover js-basic-example dataTable" style="width:100%;">
                            <thead>
                            <tr>
                                <th>ID Peramalan</th>
                                <th>Tanggal Peramalan</th>
                                <th>Bulan Peramalan</th>
                                <th>Produk Darah</th>
                                <th>Golongan Darah</th>
                                <th>Hasil</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($data as $a)
                                <tr>
                                    <td>{{ $a->id_peramalan }}</td>
                                    <td>{{ $a->tgl_peramalan }}</td>
                                    <td>{{ $a->bulan_peramalan }}</td>
                                    <td>{{ $a->komponen }}</td>
                                    <td>{{ $a->golDarah }}</td>
                                    <td>{{ $a->hasil }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{--<div class="row clearfix">--}}
        {{--<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">--}}
            {{--<div class="card">--}}
                {{--<div class="header">--}}
                    {{--<h2>--}}
                        {{--Coba Peramalan--}}
                    {{--</h2>--}}
                {{--</div>--}}
                {{--<div class="body">--}}
                    {{--<div class="table-responsive">--}}
                        {{--<?php--}}
                        {{--$permintaan = DB::table('tb_permintaan')--}}
                            {{--->select(DB::raw('sum(jumlah_permintaan) as `permintaan`'),DB::raw('MONTH(tanggal_permintaan) month'))--}}
                            {{--->where('komponen', 'WB')--}}
                            {{--->where('golongan_darah', 'O')--}}
                            {{--->groupby('month')--}}
                            {{--->get();--}}
                        {{--$n=intval($permintaan->count());--}}
                        {{--$jumlah_x = 0;--}}
                        {{--$jumlah_y = 0;--}}
                        {{--$jumlah_xx = 0;--}}
                        {{--$jumlah_xy = 0;--}}
                        {{--$x1 = $n+1;--}}
                        {{--?>--}}
                        {{--<table class="table table-responsive table-bordered table-striped table-hover js-basic-example dataTable" style="width:100%;">--}}
                            {{--<thead>--}}
                            {{--<tr>--}}
                                {{--<th>Bulan</th>--}}
                                {{--<th>Permintaan (WB A)</th>--}}
                                {{--<th>X</th>--}}
                                {{--<th>XY</th>--}}
                                {{--<th>XX</th>--}}
                            {{--</tr>--}}
                            {{--</thead>--}}
                            {{--<tbody>--}}
                            {{--@foreach($permintaan as $a)--}}
                                {{--<tr>--}}
                                    {{--<td>{{ $a->month }}</td>--}}
                                    {{--<td>{{ $a->permintaan }}</td>--}}
                                    {{--<td></td>--}}
                                    {{--<td></td>--}}
                                    {{--<td></td>--}}
                                {{--</tr>--}}
                            {{--@endforeach--}}
                            {{--</tbody>--}}
                        {{--</table>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}
@endsection

@section('isiLuar')
    <button type="button" class="btn bg-red waves-effect" data-toggle="modal" data-target="#largeModal">
        Peramalan Baru
    </button>
    <div class="modal fade" id="largeModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="largeModalLabel">Tambah Peramalan</h4>
                </div>
                <div class="modal-body">
                    {!! Form::open(['url'=>route('peramalan.store')]) !!}

                    <div class="row clearfix">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <select name="komponen" class="form-control">
                                        <option value="">-- Produk Darah --</option>
                                        <option value="WB">WB</option>
                                        <option value="PRC">PRC</option>
                                        <option value="TC">TC</option>
                                        <option value="LP">LP</option>
                                        <option value="FFP">FFP</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <select name="golDarah" class="form-control">
                                        <option value="">-- Gol Darah --</option>
                                        <option value="A">A</option>
                                        <option value="B">B</option>
                                        <option value="AB">AB</option>
                                        <option value="O">O</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="submit" class="btn btn-link waves-effect">RAMAL</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">TUTUP</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/admin/permintaan.blade.php
@extends('layouts.header')
@section('title')
    Permintaan - Admin
@endsection

@section('isiLuarAtas')
    Permintaan
@endsection

@section('konten')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Tabel Permintaan
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-responsive table-bordered table-striped table-hover js-basic-example dataTable" style="width:100%;">
                            <thead>
                            <tr>
                                <th>ID Permintaan</th>
                                <th>Tanggal Permintaan</th>
                                <th>Komponen</th>
                                <th>Golongan Darah</th>
                                <th>Rhesus</th>
                                <th>Jumlah Permintaan</th>
                                <th>Nama RS</th>
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($data as $a)
                                <tr>
                                    <td>{{ $a->id_permintaan }}</td>
                                    <td>{{ $a->tanggal_permintaan }}</td>
                                    <td>{{ $a->komponen }}</td>
                                    <td>{{ $a->golongan_darah }}</td>
                                    <td>{{ $a->rhesus }}</td>
                                    <td>{{ $a->jumlah_permintaan }}</td>
                                    <td>{{ $a->name }}</td>
                                    <td class="text-center">
                                        @if ($a->status == 0)
                                            <a href="{{route("validasiPermintaan", $a->id_permintaan)}}" class="validasi" data-confirm="Apakah anda yakin ingin memvalidasi ID Permintaan : {{ $a->id_permintaan }}, Jumlah Permintaan : {{ $a->jumlah_permintaan }} ?"><i class="material-icons" style="color : #0e90d2">help</i></a>
                                        @else
                                            <a href="{{route("batalkanPermintaan", $a->id_permintaan)}}" class="validasi" data-confirm="Apakah anda yakin ingin membatalkan validasi ID Permintaan : {{ $a->id_permintaan }}, Jumlah Permintaan : {{ $a->jumlah_permintaan }} ?"><i class="material-icons" style="color : green">check_circle</i></a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('isiLuar')

@endsection

resources/views/admin/stok.blade.php
@extends('layouts.header')
@section('title')
    Stok Darah - Admin
@endsection

@section('isiLuarAtas')
    Stok Darah
@endsection

@section('konten')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Tabel Stok Darah
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-responsive table-bordered table-striped table-hover js-basic-example dataTable" style="width:100%;">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>Komponen</th>
                                <th>Golongan Darah</th>
                                <th>Stok</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $no=1 ?>
                            @foreach($data as $a)
                                <tr>
                                    <td>{{ $no }}</td>
                                    <td>{{ $a->komponen }}</td>
                                    <td>{{ $a->golDarah }}</td>
                                    <td>
                                        <?php $d = DB::table('tb_donor')->join('tb_kantong', 'tb_kantong.idDonor', '=', 'tb_donor.idDonor')->join('tb_pendonor', 'tb_donor.noKTP', '=', 'tb_pendonor.noKTP')->where([['komponen', '=', $a->komponen], ['golDarah', '=', $a->golDarah],])->get() ?>
                                        {{ $stok = count($d) }}
                                    </td>
                                </tr>
                                <?php $no++;?>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('isiLuar')

@endsection