routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('landing');
});

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

//Landing Page
Route::get('/home', 'HomeController@index')->name('home');
Route::get('landing', 'landingController@index');

//Beranda
Route::get('beranda', 'berandaController@index');

//Stok Darah
Route::resource('stok', 'stokController');
Route::post('/updateStok', ['as' => 'updateStok', 'uses' => 'stokController@update']);

//Permintaan
Route::resource('permintaan', 'permintaanController');
Route::get('/validasiPermintaan/{id}', ['as' => 'validasiPermintaan', 'uses' => 'permintaanController@validasi']);
Route::get('/batalkanPermintaan/{id}', ['as' => 'batalkanPermintaan', 'uses' => 'permintaanController@batalvalidasi']);

//Pendonor
Route::resource('pendonor', 'pendonorController');
Route::post('/updatePendonor', ['as' => 'updatePendonor', 'uses' => 'pendonorController@update']);
Route::get('/hapusPendonor/{id}', ['as' => 'hapusPendonor', 'uses' => 'pendonorController@destroy']);

//Donor
Route::resource('donor', 'donorController');
Route::post('/updateDonor', ['as' => 'updateDonor', 'uses' => 'donorController@update']);
Route::get('/hapusDonor/{id}', ['as' => 'hapusDonor', 'uses' => 'donorController@destroy']);

//Peramalan
Route::resource('peramalan', 'peramalanController');

resources/views/manajer/beranda.blade.php
@extends('layouts.header')
@section('title')
    Beranda - Manajer
@endsection

@section('isiLuarAtas')
    Beranda
@endsection

@section('konten')
    <!-- Widgets -->
    <div class="row clearfix">
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-pink hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">assignment</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Total Permintaan</div>
                    <div class="number count-to">{{$totalpermintaan}}</div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-cyan hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">assignment_turned_in</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Tervalidasi</div>
                    <div class="number count-to">{{$permintaantervalidasi}}</div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-light-green hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">assignment_late</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Belum Tervalidasi</div>
                    <div class="number count-to">{{$permintaanbelum}}</div>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
            <div class="info-box bg-orange hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">opacity</i>
                </div>
                <div class="content">
                    <div class="text text-uppercase">Stok Darah Total</div>
                    <div class="number count-to">{{$stok}}</div>
                </div>
            </div>
        </div>
    </div>
    <!-- #END# Widgets -->

    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="body text-center">
                    <img src="{{ asset('images/logo_pmi.png') }}" style="height: 250px;">
                    <h1>Selamat Datang {{ Auth::user()->name }}</h1>
                    <p class="m-b-30">
                        Selamat datang di Sistem Informasi UTD PMI Kab. Jombang. Silahkan pilih menu yang tersedia untuk mulai mengoperasikan sistem informasi ini.
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('isiLuar')

@endsection

resources/views/manajer/permintaan.blade.php
@extends('layouts.header')
@section('title')
    Permintaan - Admin
@endsection

@section('isiLuarAtas')
    Permintaan
@endsection

@section('konten')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Tabel Permintaan
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-responsive table-bordered table-striped table-hover js-basic-example dataTable" style="width:100%;">
                            <thead>
                            <tr>
                                <th>ID Permintaan</th>
                                <th>Tanggal Permintaan</th>
                                <th>Komponen</th>
                                <th>Golongan Darah</th>
                                <th>Rhesus</th>
                                <th>Jumlah Permintaan</th>
                                <th>Nama RS</th>
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($data as $a)
                                <tr>
                                    <td>{{ $a->id_permintaan }}</td>
                                    <td>{{ $a->tanggal_permintaan }}</td>
                                    <td>{{ $a->komponen }}</td>
                                    <td>{{ $a->golongan_darah }}</td>
                                    <td>{{ $a->rhesus }}</td>
                                    <td>{{ $a->jumlah_permintaan }}</td>
                                    <td>{{ $a->name }}</td>
                                    <td class="text-center">
                                        @if ($a->status == 0)
                                            <i class="material-icons" style="color: #0e90d2">help</i>
                                        @else
                                            <i class="material-icons" style="color : green">check_circle</i>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('isiLuar')
    <button type="button" class="btn bg-red waves-effect" data-toggle="modal" data-target="#largeModal">
        Data Baru
    </button>
    <div class="modal fade" id="largeModal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="largeModalLabel">Tambah Permintaan</h4>
                </div>
                <div class="modal-body">
                    {!! Form::open(['url'=>route('permintaan.store')]) !!}
                    <div class="row clearfix">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <select name="komponen" class="form-control">
                                        <option value="">-- Komponen --</option>
                                        <option value="WB">WB</option>
                                        <option value="PRC">PRC</option>
                                        <option value="TC">TC</option>
                                        <option value="LP">LP</option>
                                        <option value="FFP">FFP</option>
                                        <option value="FP">FP</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <select name="goldar" class="form-control">
                                        <option value="">-- goldar --</option>
                                        <option value="A">A</option>
                                        <option value="B">B</option>
                                        <option value="O">O</option>
                                        <option value="AB">AB</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row clearfix">
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <select name="rhesus" class="form-control">
                                        <option value="">-- rhesus --</option>
                                        <option value="+">+</option>
                                        <option value="-">-</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-line">
                                    <input name="jumlah" type="text" class="form-control" placeholder="Jumlah">
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-link waves-effect">SIMPAN</button>
                    <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">TUTUP</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
@endsection

resources/views/manajer/stok.blade.php
@extends('layouts.header')
@section('title')
    Stok Darah - Manajer
@endsection

@section('isiLuarAtas')
    Stok Darah
@endsection

@section('konten')
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <h2>
                        Tabel Stok Darah
                    </h2>
                </div>
                <div class="body">
                    <div class="table-responsive">
                        <table class="table table-responsive table-bordered table-striped table-hover js-basic-example dataTable" style="width:100%;">
                            <thead>
                            <tr>
                                <th>No.</th>
                                <th>Komponen</th>
                                <th>Golongan Darah</th>
                                <th>Stok</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $no=1 ?>
                            @foreach($data as $a)
                                <tr>
                                    <td>{{ $no }}</td>
                                    <td>{{ $a->komponen }}</td>
                                    <td>{{ $a->golDarah }}</td>
                                    <td>
                                        <?php $d = DB::table('tb_donor')->join('tb_kantong', 'tb_kantong.idDonor', '=', 'tb_donor.idDonor')->join('tb_pendonor', 'tb_donor.noKTP', '=', 'tb_pendonor.noKTP')->where([['komponen', '=', $a->komponen], ['golDarah', '=', $a->golDarah],])->get() ?>
                                        {{ $stok = count($d) }}
                                    </td>
                                </tr>
                                <?php $no++;?>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('isiLuar')

@endsection